{
    "name": "FEL Guatemala - Swift Solutions",
    "version": "2.0",
    "depends": ["base", "account", "account_accountant", "account_debit_note", "base_fel", "purchase"],
    "assets": {"web.assets_qweb": ["fel/static/src/css/reporte_factura.css"]},
    "data": [
        "security/ir.model.access.csv",
        "report/report_invoice_document_swift.xml",
        "views/account_move_special_invoice_menu.xml",
        "views/account_move_special_invoice_view.xml",
        "views/account_move_inherit_view.xml",
        "views/account_journal_inherit_view.xml",
        "views/wizard_anular_facturas_view.xml",
        "views/account_move_fact_type.xml",
        "views/account_move_nota_debito_view.xml",
        "views/account_move_nota_debito_menu_view.xml",
        "views/account_move_exportacion_view.xml",
        "views/res_partner_information_view.xml",
        "views/account_move_supplier_invoice.xml",
        "views/account_move_posiciones_fiscales.xml",
        "views/account_move_customer_invoice.xml",
        "views/account_move_vendor_invoice.xml",
        "views/account_payment_form_view.xml",
    ],
    "installable": True,
    "application": False,
}
